### ISSUE TITLE
Ubuntu/Debian yarn add firebase error + fix

### ISSUE THREAD

**Issue by mashcode** [dingaaling/citi-map#13]
(myenv) marc@penguin:~/citi-map$ yarn add firebase
yarn add v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error @testing-library/react@12.1.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

To resolve must grab the latest node version from Nodesource: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

To install: sudo apt-get install -y nodejs

Some dependency errors and package build info

warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > material-ui@0.20.2" has incorrect peer dependency "react@^15.4.0 || ^16.0.0".
warning " > material-ui@0.20.2" has incorrect peer dependency "react-dom@^15.4.0 || ^16.0.0".
warning "material-ui > react-event-listener@0.6.6" has incorrect peer dependency "react@^16.3.0".
warning "material-ui > react-transition-group@1.2.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "material-ui > react-transition-group@1.2.1" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning "material-ui > recompose@0.26.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-leaflet@2.7.0" has incorrect peer dependency "react@^16.8.0".
warning " > react-leaflet@2.7.0" has incorrect peer dependency "react-dom@^16.8.0".
warning "react-scripts > tailwindcss@3.0.19" has unmet peer dependency "autoprefixer@^10.0.2".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.0" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 43 new dependencies.
info Direct dependencies
└─ firebase@9.6.8
info All dependencies
├─ @firebase/analytics-compat@0.1.6
├─ @firebase/analytics-types@0.7.0
├─ @firebase/app-check-compat@0.2.3
├─ @firebase/app-check-interop-types@0.1.0
├─ @firebase/app-compat@0.1.19
├─ @firebase/auth-compat@0.2.9
├─ @firebase/auth-types@0.11.0
├─ @firebase/database-compat@0.1.5
├─ @firebase/database-types@0.9.4
├─ @firebase/firestore-compat@0.1.14
├─ @firebase/firestore-types@2.5.0
├─ @firebase/functions-compat@0.1.9
├─ @firebase/functions-types@0.5.0
├─ @firebase/messaging-compat@0.1.9
├─ @firebase/performance-compat@0.1.5
├─ @firebase/performance-types@0.1.0
├─ @firebase/polyfill@0.3.36
├─ @firebase/remote-config-compat@0.1.5
├─ @firebase/remote-config-types@0.2.0
├─ @firebase/storage-compat@0.1.10
├─ @firebase/storage-types@0.6.0
├─ @firebase/webchannel-wrapper@0.6.1
├─ @grpc/grpc-js@1.5.8
├─ @grpc/proto-loader@0.6.9
├─ @protobufjs/aspromise@1.1.2
├─ @protobufjs/base64@1.1.2
├─ @protobufjs/codegen@2.0.4
├─ @protobufjs/eventemitter@1.1.0
├─ @protobufjs/fetch@1.1.0
├─ @protobufjs/float@1.0.2
├─ @protobufjs/path@1.1.2
├─ @protobufjs/pool@1.1.0
├─ @protobufjs/utf8@1.1.0
├─ core-js@3.6.5
├─ firebase@9.6.8
├─ immediate@3.0.6
├─ lie@3.3.0
├─ lodash.camelcase@4.3.0
├─ pako@1.0.11
├─ promise-polyfill@8.1.3
├─ protobufjs@6.11.2
├─ selenium-webdriver@4.0.0-rc-1
└─ set-immediate-shim@1.0.1

**Comment by mashcode** [comment]
Closing...with prejudice :-)

**Comment by MarcoBerlot** [comment]
Hey @mashcode, glad you found a solution, in general, we recommend to use node 16.0.0 or higher

**Comment by mashcode** [comment]
Funny. The latest stable node release from ubuntu/debian is 10.x. Of course
this is the detached Chromebook linux so it's not at all surprising :-)
