### ISSUE TITLE
Firebase hosting blank browser display?

### ISSUE THREAD

**Issue by mashcode** [dingaaling/citi-map#14]
Hi, Set up firebase hosting yet the page displays blank. Is it because it's a test vs production database?  I guess I'm just not sure how to debug this. Any ideas? Seems like it's a firebase config problem?

Project Console: https://console.firebase.google.com/project/street-furniture-e24a4/overview
Hosting URL: https://street-furniture-e24a4.web.app

Chrome inspector shows these errors:
﻿manifest.json:1 GET https://street-furniture-e24a4.web.app/%PUBLIC_URL%/manifest.json 400
manifest.json:1 Manifest: Line: 1, column: 5, Unexpected data after root element.
The attempt to bind "/%PUBLIC_URL%/manifest.json" in the workspace failed as this URI is malformed.
manifest.json:1 Failed to load resource: the server responded with a status of 400 ()

**Comment by MarcoBerlot** [comment]
Hi @mashcode,

Does your application run in your local? Can you share a screenshot of the output of `yarn run`? 
If that works, are you sure you ran `yarn build` and then `firebase deploy`?

**Comment by MarcoBerlot** [comment]
Hi @mashcode, generally you can avoid this situation by using `build` instead of `public` during the firebase init.

You can check step 6 in the `Hosting the App on Firebase` section of the readme
