### ISSUE TITLE
[NYC ODW 2022 ]What kinds of urban data or behaviors are of interest to collect?

### ISSUE THREAD

**Issue by dingaaling** [dingaaling/citi-map#5]

**Comment by vhellon** [comment]
Just one from me- street lighting!

**Comment by MarcoBerlot** [comment]
- Cars parked on bike lines. 
- Street Artists currently performing 
- Covid 19 Mobile Testing Centers

**Comment by hydrosquall** [comment]
Some areas of interest (also happy to team up with others!)

- Street Art (loosely interpreted)
- Noise level
- Prevalence of pet poop on the sidewalk

**Comment by tgb417** [comment]
Inaccessible public accommodations like: 

- subway stations without working elevators. Or elevators that need cleaning because they have been used as bathrooms.
- Sidewalks without curb cuts.
- sidewalks that are un-passable because of condition problems

**Comment by mashcode** [comment]
Public drinking water dispensers
